# Generated by Django 6.0.2 on 2026-02-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('github', 'GitHub')], default='google', max_length=50)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('id_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_auths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Authentication Provider',
                'verbose_name_plural': 'External Authentication Providers',
                'indexes': [models.Index(fields=['provider', 'provider_user_id'], name='posts_exter_provide_bbecae_idx'), models.Index(fields=['user', 'provider'], name='posts_exter_user_id_72bfff_idx')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
