# Generated by Django 6.0.1 on 2026-03-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
        ('posts', '0003_post_metadata_post_post_type_post_title'),
    ]

    operations = [
    ]
